version: "3.3"

services:

  database:
    ports:
      - 3306

  php:
    volumes:
      # Mount cached files by Composer from the host.
      - $HOME/.composer/cache/files:/home/wodby/.composer/cache/files

  webserver:
    environment:
      APACHE_FCGI_PROXY_TIMEOUT: 3600 # Do not "Gateway timeout" while I am debugging with xDebug.
